//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pilkngton.ProjectPaint.PaintApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Camera_LineRate_Hz {
            get {
                return ((int)(this["Camera_LineRate_Hz"]));
            }
            set {
                this["Camera_LineRate_Hz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Camera1_AnalogGainSetting {
            get {
                return ((int)(this["Camera1_AnalogGainSetting"]));
            }
            set {
                this["Camera1_AnalogGainSetting"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Image_MaxBlobsSorted {
            get {
                return ((int)(this["Image_MaxBlobsSorted"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("195")]
        public int Image_Threshold {
            get {
                return ((int)(this["Image_Threshold"]));
            }
            set {
                this["Image_Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Align_Cam1Startpix {
            get {
                return ((int)(this["Align_Cam1Startpix"]));
            }
            set {
                this["Align_Cam1Startpix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2047")]
        public int Align_Cam1Endpix {
            get {
                return ((int)(this["Align_Cam1Endpix"]));
            }
            set {
                this["Align_Cam1Endpix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Align_Cam2Startpix {
            get {
                return ((int)(this["Align_Cam2Startpix"]));
            }
            set {
                this["Align_Cam2Startpix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2047")]
        public int Align_Cam2Endpix {
            get {
                return ((int)(this["Align_Cam2Endpix"]));
            }
            set {
                this["Align_Cam2Endpix"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int Align_NumZones {
            get {
                return ((int)(this["Align_NumZones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public int Camera_WidthPixels {
            get {
                return ((int)(this["Camera_WidthPixels"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public double Image_OverloadFactor {
            get {
                return ((double)(this["Image_OverloadFactor"]));
            }
            set {
                this["Image_OverloadFactor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Align_Cam1Startmm {
            get {
                return ((double)(this["Align_Cam1Startmm"]));
            }
            set {
                this["Align_Cam1Startmm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2003")]
        public double Align_Cam1Endmm {
            get {
                return ((double)(this["Align_Cam1Endmm"]));
            }
            set {
                this["Align_Cam1Endmm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3745")]
        public double Align_Cam2Endmm {
            get {
                return ((double)(this["Align_Cam2Endmm"]));
            }
            set {
                this["Align_Cam2Endmm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1748")]
        public double Align_Cam2Startmm {
            get {
                return ((double)(this["Align_Cam2Startmm"]));
            }
            set {
                this["Align_Cam2Startmm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int Image_MaxNumBlobs {
            get {
                return ((int)(this["Image_MaxNumBlobs"]));
            }
            set {
                this["Image_MaxNumBlobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238")]
        public double Align_ZoneSizemm {
            get {
                return ((double)(this["Align_ZoneSizemm"]));
            }
            set {
                this["Align_ZoneSizemm"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Report_BinnIntervalMins {
            get {
                return ((int)(this["Report_BinnIntervalMins"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int Camera_FrameHeightPixels {
            get {
                return ((int)(this["Camera_FrameHeightPixels"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Report_BinnDays {
            get {
                return ((int)(this["Report_BinnDays"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Report_BlipStartOnly {
            get {
                return ((bool)(this["Report_BlipStartOnly"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Report_MapUpdateSeconds {
            get {
                return ((int)(this["Report_MapUpdateSeconds"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Image_Blob1StartPix {
            get {
                return ((int)(this["Image_Blob1StartPix"]));
            }
            set {
                this["Image_Blob1StartPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2047")]
        public int Image_Blob1EndPix {
            get {
                return ((int)(this["Image_Blob1EndPix"]));
            }
            set {
                this["Image_Blob1EndPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Image_Blob2StartPix {
            get {
                return ((int)(this["Image_Blob2StartPix"]));
            }
            set {
                this["Image_Blob2StartPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2047")]
        public int Image_Blob2EndPix {
            get {
                return ((int)(this["Image_Blob2EndPix"]));
            }
            set {
                this["Image_Blob2EndPix"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Alarm_Cam2LightFailEnable {
            get {
                return ((bool)(this["Alarm_Cam2LightFailEnable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Alarm_Cam2LightFailedCount {
            get {
                return ((int)(this["Alarm_Cam2LightFailedCount"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Image_BlobMinAreaPixels {
            get {
                return ((int)(this["Image_BlobMinAreaPixels"]));
            }
            set {
                this["Image_BlobMinAreaPixels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Report_BlipSmallAreaPix {
            get {
                return ((int)(this["Report_BlipSmallAreaPix"]));
            }
            set {
                this["Report_BlipSmallAreaPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int Report_BlipMediumAreaPix {
            get {
                return ((int)(this["Report_BlipMediumAreaPix"]));
            }
            set {
                this["Report_BlipMediumAreaPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int Report_BlipLargeAreaPix {
            get {
                return ((int)(this["Report_BlipLargeAreaPix"]));
            }
            set {
                this["Report_BlipLargeAreaPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Report_StreamSmallWidthPix {
            get {
                return ((int)(this["Report_StreamSmallWidthPix"]));
            }
            set {
                this["Report_StreamSmallWidthPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Report_StreamMediumWidthPix {
            get {
                return ((int)(this["Report_StreamMediumWidthPix"]));
            }
            set {
                this["Report_StreamMediumWidthPix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Report_StreamLargeWidthPix {
            get {
                return ((int)(this["Report_StreamLargeWidthPix"]));
            }
            set {
                this["Report_StreamLargeWidthPix"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\Paint Data\\\\")]
        public string Report_ImageDir {
            get {
                return ((string)(this["Report_ImageDir"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Report_ImageSaveFlags {
            get {
                return ((int)(this["Report_ImageSaveFlags"]));
            }
            set {
                this["Report_ImageSaveFlags"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double Image_WhiteBoardFactor {
            get {
                return ((double)(this["Image_WhiteBoardFactor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int OPC_ServerRegistrationAction {
            get {
                return ((int)(this["OPC_ServerRegistrationAction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Image_CalbackTimeMsgEnable {
            get {
                return ((bool)(this["Image_CalbackTimeMsgEnable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password")]
        public string System_Password {
            get {
                return ((string)(this["System_Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool System_PasswordEnabled {
            get {
                return ((bool)(this["System_PasswordEnabled"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Camera2_AnalogGainSetting {
            get {
                return ((int)(this["Camera2_AnalogGainSetting"]));
            }
            set {
                this["Camera2_AnalogGainSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1950")]
        public int Camera2_LastPixelforWidth1 {
            get {
                return ((int)(this["Camera2_LastPixelforWidth1"]));
            }
            set {
                this["Camera2_LastPixelforWidth1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1800")]
        public int Camera2_LastPixelforWidth2 {
            get {
                return ((int)(this["Camera2_LastPixelforWidth2"]));
            }
            set {
                this["Camera2_LastPixelforWidth2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paint Red.jpg")]
        public string GUI_LogoFile {
            get {
                return ((string)(this["GUI_LogoFile"]));
            }
            set {
                this["GUI_LogoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Report_BlipDigOutOnTime_ms {
            get {
                return ((int)(this["Report_BlipDigOutOnTime_ms"]));
            }
            set {
                this["Report_BlipDigOutOnTime_ms"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Report_DigOutLinesDisabled {
            get {
                return ((bool)(this["Report_DigOutLinesDisabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Camera_CommsEnabled {
            get {
                return ((bool)(this["Camera_CommsEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int Image_FeintStreamNumFrames {
            get {
                return ((int)(this["Image_FeintStreamNumFrames"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Report_FeintStreams {
            get {
                return ((bool)(this["Report_FeintStreams"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Image_FeintStreamOffsetThreshold {
            get {
                return ((int)(this["Image_FeintStreamOffsetThreshold"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Image_FeintStreamPolyOrder {
            get {
                return ((int)(this["Image_FeintStreamPolyOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Image_FeintStreamFIRnotPolyFit {
            get {
                return ((bool)(this["Image_FeintStreamFIRnotPolyFit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Image_FeintStreamMinSize_mm {
            get {
                return ((double)(this["Image_FeintStreamMinSize_mm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double Image_FeintStreamMaxSize_mm {
            get {
                return ((double)(this["Image_FeintStreamMaxSize_mm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int Image_FeintStreamFIRWidth {
            get {
                return ((int)(this["Image_FeintStreamFIRWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_EnableOPC {
            get {
                return ((bool)(this["APP_EnableOPC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APP_EnableFeintProcessing {
            get {
                return ((bool)(this["APP_EnableFeintProcessing"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Image_BlobLightFieldNotDark {
            get {
                return ((bool)(this["Image_BlobLightFieldNotDark"]));
            }
            set {
                this["Image_BlobLightFieldNotDark"] = value;
            }
        }
    }
}
